services:
  mysql:
    image: mysql:8.4
    container_name: lms-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: lms_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - lms_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  lms_mysql_data:
